version: '3.8'

services:
  web:
    build: .
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
       - 8000
    env_file:
      - ./.env

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ovhack
      - POSTGRES_PASSWORD=ovhack
      - POSTGRES_DB=h4x0r

  nginx:
    build: ./nginx
    ports:
      - 36811:80
    volumes:
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:

