# Generated by Django 5.0.6 on 2024-09-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_member_secret_question_member_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_data',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
